###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

###
GET http://localhost:3000/chat/conversation/user/837f47f0-ecf4-4f7f-98b2-b07233ae7a15

###
GET http://localhost:3000/chat/history?conversation_id=977e2bb2-e344-4da8-98cd-fa3ef1bda43a&user_id=837f47f0-ecf4-4f7f-98b2-b07233ae7a15
